#include "Sim/Simulation.h"
#include "Sim/MapDefinition.h"
#include <iostream>
#include <iomanip>
#include <algorithm>
#include <array>
#include <cmath>
using namespace cinder;
float distanceSq(Vec2 a,Vec2 b){return (a.x-b.x)*(a.x-b.x)+(a.y-b.y)*(a.y-b.y);}
float surfaceMaximum(const MapDefinition&m,int x,int y){float h=0;for(float fy:{.001f,.5f,.999f})for(float fx:{.001f,.5f,.999f})h=std::max(h,m.terrainHeight({(x+fx)*75,(y+fy)*75}));return h;}
float required(const MapDefinition&m,int x,int y){return m.terrainVisibilityHeight({{(x+.5f)*75,(y+.5f)*75},{37.5f,37.5f}});}
int state(const Simulation&s,int x,int y){Vec2 p{(x+.5f)*75,(y+.5f)*75};return s.visible(0,p)?2:s.explored(0,p)?1:0;}
void counts(const Simulation&s){int n[3]={};for(int y=0;y<64;++y)for(int x=0;x<64;++x)++n[state(s,x,y)];std::cout<<"COUNTS tick="<<s.tick()<<" unknown="<<n[0]<<" explored="<<n[1]<<" visible="<<n[2]<<"\n";}
void sources(const Simulation&s,const MapDefinition&m,int x,int y){Vec2 p{(x+.5f)*75,(y+.5f)*75};float h=required(m,x,y);std::cout<<"CELL tick="<<s.tick()<<" x="<<x<<" y="<<y<<" center="<<p.x<<","<<p.y<<" requiredHeight="<<h<<" maxSurfaceHeight="<<surfaceMaximum(m,x,y)<<" state="<<state(s,x,y)<<"\n";for(const auto&e:s.entities()){if(!e.alive()||e.team!=0||e.kind==Kind::Resource)continue;float d=std::sqrt(distanceSq(e.pos,p));float r=definition(e.kind).vision*(e.progress>=1?1:.5f)+37.5f;if(d>r)continue;float eh=m.terrainHeight(e.pos);std::cout<<"  observer="<<e.id<<" kind="<<definition(e.kind).name<<" xy="<<e.pos.x<<","<<e.pos.y<<" height="<<eh<<" distance="<<d<<" radius="<<r<<" heightAllows="<<(definition(e.kind).air||h<=eh+1)<<"\n";}}
int main(){std::cout<<std::fixed<<std::setprecision(3);Config c;c.seed=0xCA770001u;c.ai=false;Simulation s;s.reset(c);const auto&m=mapDefinition(0,2,MatchLength::Standard,1);std::vector<Id> defenders;auto spawn=[&](Kind k,Vec2 p){std::string why;if(definition(k).building&&!s.canPlace(0,k,p,&why)){std::cerr<<"CANPLACE FAILED "<<why<<"\n";exit(1);}Id id=s.debugSpawn(k,0,p);std::cout<<"SPAWN "<<id<<" "<<definition(k).name<<" "<<p.x<<","<<p.y<<"\n";return id;};defenders.push_back(spawn(Kind::Scout,{2240,1350}));spawn(Kind::Headquarters,{2260,950});Id foundry=spawn(Kind::Foundry,{1180,820});spawn(Kind::Processor,{1180,500});spawn(Kind::Turret,{1300,1350});Id striker=spawn(Kind::Striker,{1360,1190});defenders.push_back(striker);Id lancer=spawn(Kind::Lancer,{1770,1230});defenders.push_back(lancer);defenders.push_back(spawn(Kind::Bastion,{2140,1200}));defenders.push_back(spawn(Kind::Mender,{1250,1160}));Command hold;hold.type=CommandType::Hold;hold.team=0;hold.units=defenders;if(!s.command(hold).accepted)return 2;for(const auto&site:m.sites)if(site.owner==0&&site.role==MapSiteRole::Natural){for(size_t i=0;i<site.nodes.size();++i){Vec2 n=site.nodes[i];Id target=0;for(const auto&e:s.entities())if(e.kind==Kind::Resource&&distanceSq(n,e.pos)<.001f)target=e.id;Id worker=spawn(Kind::Worker,{n.x+(i==0?-72.f:72.f),n.y+66});Command gather;gather.type=CommandType::Gather;gather.team=0;gather.units={worker};gather.target=target;if(!s.command(gather).accepted)return 3;}}
Command train;train.type=CommandType::Train;train.team=0;train.units={foundry};train.kind=Kind::Striker;if(!s.command(train).accepted)return 4;Command patrol;patrol.type=CommandType::Patrol;patrol.team=0;patrol.units={striker,lancer};patrol.point={2390,1560};if(!s.command(patrol).accepted)return 5;s.update(Simulation::Step*4);std::array<int,4096> first{};std::array<int,4096> lost{};bool ownhidden[256]={};
while(s.tick()<=104){if(s.tick()==44){counts(s);for(int y=0;y<64;++y)for(int x=0;x<64;++x)first[y*64+x]=state(s,x,y);sources(s,m,26,16);sources(s,m,25,17);}
if(s.tick()>=44){for(int y=0;y<64;++y)for(int x=0;x<64;++x){int i=y*64+x;if(first[i]==2&&state(s,x,y)<2&&!lost[i])lost[i]=s.tick();}for(const auto&e:s.entities())if(e.team==0&&e.alive()&&e.kind!=Kind::Resource){bool hidden=!s.visible(0,e.pos);if(hidden!=ownhidden[e.id]||s.tick()==44||s.tick()==104){int x=int(e.pos.x/75),y=int(e.pos.y/75);std::cout<<"UNIT tick="<<s.tick()<<" id="<<e.id<<" kind="<<definition(e.kind).name<<" xy="<<e.pos.x<<","<<e.pos.y<<" height="<<m.terrainHeight(e.pos)<<" ownCell="<<x<<","<<y<<" required="<<required(m,x,y)<<" state="<<state(s,x,y)<<"\n";}ownhidden[e.id]=hidden;}}
if(s.tick()==104){counts(s);sources(s,m,26,16);sources(s,m,25,17);for(int y=0;y<64;++y)for(int x=0;x<64;++x){int i=y*64+x,now=state(s,x,y);if(first[i]==2&&now!=2)std::cout<<"LOST x="<<x<<" y="<<y<<" old=2 new="<<now<<" firstLost="<<lost[i]<<" onRamp="<<m.onRamp({(x+.5f)*75,(y+.5f)*75})<<" required="<<required(m,x,y)<<"\n";}break;}s.update(Simulation::Step);}return 0;}
